// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

enum OracleType {
    TEE,
    ZKP
}

struct AccessProof {
    bytes32 dataHash;
    bytes targetPubkey;
    bytes nonce;
    bytes proof;
}

struct OwnershipProof {
    OracleType oracleType;
    bytes32 dataHash;
    bytes sealedKey;
    bytes targetPubkey;
    bytes nonce;
    bytes proof;
}

struct TransferValidityProof {
    AccessProof accessProof;
    OwnershipProof ownershipProof;
}

struct TransferValidityProofOutput {
    bytes32 dataHash;
    bytes sealedKey;
    bytes targetPubkey;
    bytes wantedKey;
    address accessAssistant;
    bytes accessProofNonce;
    bytes ownershipProofNonce;
}

interface IERC7857DataVerifier {
    /// @notice Verify data transfer validity
    /// @param proofs Proof generated by TEE/ZKP
    function verifyTransferValidity(
        TransferValidityProof[] calldata proofs
    ) external returns (TransferValidityProofOutput[] memory);
}
